import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Element, Link } from 'react-scroll';
import "../styles/global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headers = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div className="outer">
        <body className={inter.className}>
          {headers.map(header => (
            <Link key={header} to={header} smooth={true} offset={-30}>{header}</Link>
          ))}

          {headers.map(header => (
            <Element key={header} name={header}>
              <h1>{header}</h1>
            </Element>
          ))}

          {children}
        </body>
      </div>
    </html>
  );
}